title: Pelham Bergesen's Portfolio
description: To improve is to change; to be perfect is to change often.
- Winston Churchill
show_downloads: true
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

