title: Pelham's Portfolio
description: To improve is to change; to be perfect is to change often.
show_downloads: false
remote_theme: pages-themes/leap-day@v0.2.0
theme: just-the-docs
color_scheme: "dark"